[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[plugins]]
package = "./plugins/index.js"

  [plugins.inputs]
  ghostURL = "https://demonstration.ghost.io"
  ghostKey = "93e63c8b150f4a145c0611aed0"

[[plugins]]
package = "@netlify/plugin-local-install-core"
