[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-local-install-core"
  package = "./plugins/index.js"

  [plugins.inputs]
    ghostURL = "https://demo.ghost.io"
    ghostKey = "22444f78447824223cefc48062"
    assetsDir = "./assets/images/"
    pagesDir = "./"
    postsDir = "./_posts/"
    cacheFile = "./_data/ghostMarkdownCache.json"
